# 第三章：数字日期和时间

在 Python 中执行整数和浮点数的数学运算时很简单的。尽管如此，如果你需要执行分数、数组或者是日期和时间的运算的话，就得做更多的工作了。本章集中讨论的就是这些主题。

## 1、数字的四舍五入

**问题** 

    你想对浮点数执行指定精度的舍入运算。
    
**解决方案**

    对于简单的摄入运算，使用内置的 round(value, ndigits) 函数即可。比如：
    

In [1]:
>>> round(1.23, 1)

1.2

In [2]:
>>> round(1.27, 1)

1.3

In [3]:
>>> round(1.2334, 3)

1.233

    当一个值刚好在两个边界的中间的时候，round 函数返回离它最近的偶数。也就是说，对 1.5 或者 2.5 的舍入运算都会得到 2。
    
    传给 round() 函数的 ndigits 参数可以是负数，这种情况下，舍入运算会作用在十位、百位、千位等上面。比如：

In [4]:
>>> a = 1627731 
>>> round(a, -1)

1627730

In [5]:
>>> round(a, -2)

1627700

## 2、执行精确的浮点数运算

**问题** 

    你需要对浮点数执行精确的计算操作，并且不希望有任何小误差的出现。
    
**解决方案**

    浮点数的一个普遍问题是它们并不能精确的表示十进制数。这些错误是由底层 CPU 和 IEEE 754 标准通过自己的浮点单位去执行算术时的特征。由于 Python 的浮点数据类型使用底层表示存储数据，因此你没办法去避免这样的误差。
    
    如果你想更加精确 (并能容忍一定的性能损耗)，你可以使用 decimal 模块：

In [6]:
>>> from decimal import Decimal
>>> a = Decimal('4.2')
>>> b = Decimal('2.1')
>>> a+b

Decimal('6.3')

In [7]:
>>> print(a + b)

6.3


In [8]:
>>> (a + b) == Decimal('6.3')

True

    初看起来，上面的代码好像有点奇怪，比如我们用字符串来表示数字。然而，Decimal 对象会像普通浮点数一样的工作 (支持所有的常用数学运算)。如果你打印它们或者在字符串格式化函数中使用它们，看起来跟普通数字没什么两样。
    
    decimal 模块的一个主要特征是允许你控制计算的每一方面，包括数字位数和四舍五入运算。为了这样做，你先得创建一个本地上下文并更改它的设置，比如：

In [11]:
>>> from decimal import localcontext
>>> a = Decimal('1.3')
>>> b = Decimal('1.7')
>>> print(a / b)

0.7647058823529411764705882353


In [13]:
>>> with localcontext() as ctx:
        ctx.prec = 3
        print(a / b)

0.765


In [14]:
>>> with localcontext() as ctx:
        ctx.prec = 50
        print(a / b)

0.76470588235294117647058823529411764705882352941176


    总的来说，decimal 模块主要用在涉及到金融的领域

## 3、数字的格式化输出

**问题** 

    你需要将数字格式化输出，并控制数字的位数、对齐、千位分隔符和其他的细节。
    
**解决方案**

    格式化输出单个数字的时候，可以使用内置的 format() 函数，比如：

In [15]:
>>> x = 1234.56789

>>> # Two decimal places of accuracy
>>> format(x, '0.2f')

'1234.57'

In [16]:
>>> # Right justified in 10 chars, one-digit accuracy
>>> format(x, '>10.1f')

'    1234.6'

In [17]:
>>> # Left justified 
>>> format(x, '<10.1f')

'1234.6    '

In [18]:
>>> # Centered 
>>> format(x, '^10.1f')

'  1234.6  '

In [19]:
>>> # Inclusion of thousands separator
>>> format(x, ',')

'1,234.56789'

In [21]:
>>> format(x, '0,.1f')

'1,234.6'

    如果你想使用指数激发，将 f 改成 e 或者 E（取决于指数输出的大小写形式）。比如：

In [22]:
>>> format(x, 'e')

'1.234568e+03'

In [23]:
>>> format(x, '0.2e')

'1.23e+03'

    同时指定宽度和精度的一半形式是 '[<>^]?width[,]?(.digits)?'，其中 width 和 digits 为整数，?表示可选部分。同样的格式也被用在字符串的 format() 方法中。比如：

In [24]:
>>> 'The value is {:0,.2f}'.format(x)

'The value is 1,234.57'

**讨论**

    数字格式化输出通常是比较简单的。上面演示的技术同时适用于浮点数和 decimal 模块中的 Decimal 数字对象。

In [25]:
>>> x
>>> format(x, '0.1f')

'1234.6'

    在很多 Python 代码中会看到使用 % 来格式化数字的，比如：

In [26]:
>>> '%0.2f' % x

'1234.57'

In [27]:
>>> '%10.2f' % x

'   1234.57'

In [28]:
>>> '%-10.2f' % x

'1234.57   '

## 4、二八十六进制整数

**问题** 

    你需要转换或者输出使用二进制，八进制或十六进制表示的整数。
    
**解决方案**

    为了将整数转换为二进制、八进制或十六进制的文本串，可以分别使用 bin(), cot() 或 hex() 函数：

In [29]:
>>> x = 1234
>>> bin(x)

'0b10011010010'

In [30]:
>>> oct(x)

'0o2322'

In [31]:
>>> hex(x)

'0x4d2'

    如果，不想输出 0b, 0o, 0x 的前缀的话，可以使用 format() 函数。比如：

In [32]:
>>> format(x, 'b')

'10011010010'

In [33]:
>>> format(x, 'o')

'2322'

In [34]:
>>> format(x, 'x')

'4d2'

    整数是有符号的，如果你在处理负数的话，输出结果会包含一个符号。比如：

In [35]:
>>> x = -1234
>>> format(x, 'b')

'-10011010010'

    如果你想产生一个无符号值，你需要增加一个只是最大位长度的值。比如为了显示 32 位的值，可以像下面这样写：

In [36]:
>>> x = -1234
>>> format(x + 2**32, 'b')

'11111111111111111111101100101110'

In [37]:
>>> format(x + 2**32, 'x')

'fffffb2e'

    为了以不同的进制转换整数字符串，简单的使用带有进制的 int() 函数即可：

In [38]:
>>> int('4d2', 16)

1234

In [39]:
>>> int('10011010010', 2)

1234

In [41]:
>>> int('755', 8)

493

## 5、字节到大整数的打包与解包

**问题** 

    你有一个字节字符串并想将它解压成一个整数。或者，你需要将一个大整数转换为一个字节字符串
    
**解决方案**

    假设你的程序需要处理一个拥有 128 位长的 16 个元素的字节字符串。比如：

In [42]:
data = b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'

    为了将 bytes 解析为整数，使用 int.from_bytes() 方法，并像下面这样指定字节顺序：

In [43]:
>>> len(data)

16

In [45]:
>>> int.from_bytes(data, 'little')

69120565665751139577663547927094891008

In [46]:
>>> int.from_bytes(data, 'big')

94522842520747284487117727783387188

    为了将一个大整数转换成一个字节字符串，使用 int.to_bytes() 方法，并像下面这样指定字节数和字节顺序：

In [54]:
>>> x = 94522842520747284487117727783387188
>>> x.to_bytes(16, 'big')

b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'

In [48]:
>>> x.to_bytes(16, 'little')

b'4\x00#\x00\x01\xef\xcd\x00\xab\x90x\x00V4\x12\x00'

**讨论**

    大整数和字节字符串之间的转换操作并不常见。然而，在一些应用领域有时候也会出现，比如密码学或者网络。例如IPv6 网络地址使用一个 128 位的整数表示。
    
    字节顺序规则（little 或 big）仅仅制定了构建整数时的字节的地位高位排列方式。我们从下面精心构造的 16 进制数的表示中可以很容易的看出来：

In [51]:
>>> x = 0x01020302 
>>> x.to_bytes(4, 'big')

b'\x01\x02\x03\x02'

In [52]:
>>> x.to_bytes(4, 'little') 

b'\x02\x03\x02\x01'

## 6、复数的数学运算

**问题** 

    你写的最新的网络认证方案代码遇到了一个难题，并且你唯一的解决办法就是使 用复数空间。再或者是你仅仅需要使用复数来执行一些计算操作。
    
**解决方案**

    复数可以用使用函数 complex(real, imag) 或者是带有后缀 j 的浮点数来指定。比如：

In [56]:
>>> a = complex(2, 4)
>>> b = 3 -5j
>>> a

(2+4j)

In [57]:
>>> b

(3-5j)

    对应的实部、虚部和共轭复数可以很容易的获取。就像下面这样：

In [58]:
>>> a.real

2.0

In [59]:
>>> a.imag

4.0

In [60]:
>>> a.conjugate()

(2-4j)

    另外，所有常见的数学运算都可以工作：

In [61]:
>>> a + b

(5-1j)

In [62]:
>>> a * b

(26+2j)

In [63]:
>>> a / b

(-0.4117647058823529+0.6470588235294118j)

In [64]:
>>> abs(a)

4.47213595499958

    如果要执行其他的复数函数比如正弦、余弦或平方根，使用 cmath 模块：

In [67]:
>>> import cmath
>>> cmath.sin(a)

(24.83130584894638-11.356612711218173j)

In [68]:
>>> cmath.cos(a)

(-11.36423470640106-24.814651485634183j)

In [69]:
>>> cmath.exp(a)

(-4.829809383269385-5.5920560936409816j)

## 7、无穷大与 NaN

**问题** 

    你想创建或测试正无穷、负无穷或 NaN(非数字) 的浮点数。
    
**解决方案**

    Python 并没有特殊的语法来表示这些特殊的浮点值，但是可以使用 float() 来创建它们。比如：

In [71]:
>>> a = float('inf')
>>> b = float('-inf')
>>> c = float('nan')

In [72]:
>>> a

inf

In [73]:
>>> b

-inf

In [74]:
>>> c

nan

    为了测试这些值的存在，使用 math.isinf() 和 math.isnan() 函数。比如：

In [76]:
>>> import math
>>> math.isinf(a)

True

In [77]:
>>> math.isnan(c)

True

**讨论**

    想了解更多这些特殊浮点值的信息，可以参考 IEEE 754 规范。然而，也有一些地方需要你特别注意，特别是跟比较和操作符相关的时候。
    
    无穷大数在执行数学计算的时候会传播，比如：

In [79]:
>>> a = float('inf')
>>> a + 45

inf

In [80]:
>>> a * 10

inf

In [81]:
>>> 10 / a

0.0

    但是有些操作时未定义的并会返回一个 NaN 结果。比如：

In [82]:
>>> a / a

nan

In [83]:
>>> a + b

nan

    NaN 值会在所有操作中传播，而不会产生异常。比如：

In [85]:
>>> c + 23

nan

In [86]:
>>> c/2

nan

In [88]:
>>> math.sqrt(c)

nan

    NaN 值的一个特别的地方时它们之间的比较操作总是返回 False。比如：

In [89]:
>>> d = float('nan')
>>> c == d

False

In [91]:
>>> c is d

False

    由于这个原因，测试一个 NaN 值得唯一安全的方法就是使用 math.isnan() ，也 就是上面演示的那样。


## 8、分数运算

**问题** 

    你进入时间机器，突然发现你正在做小学家庭作业，并涉及到分数计算问题。或者你可能需要写代码去计算在你的木工工厂中的测量值。
    
**解决方案**

    fractions 模块可以被用来执行包含分数的数学运算。比如：

In [2]:
>>> from fractions import Fraction
>>> a = Fraction(5, 4)
>>> b = Fraction(7, 16)
>>> print(a + b)

27/16


In [4]:
>>> c = a * b
>>> c.numerator # 分子

35

In [6]:
>>> c.denominator # 分母

64

In [7]:
>>> # Converting to a float
>>> float(c)

0.546875

In [9]:
>>> # Limit the denominator of a value
>>> print(c.limit_denominator(8))

4/7


In [11]:
>>> # Converting a float to a fraction
>>> x = 3.75
>>> y = Fraction(*x.as_integer_ratio())
>>> y

Fraction(15, 4)

## 9、大型数组运算

**问题** 

    你需要在大数据集 (比如数组或网格) 上面执行计算.
    
**解决方案**

    设计到数组的重量级运算操作，可以使用 NumPy 库。NumPy 的一个主要特征是它会给 Python 提供一个数组对象，相比标准的 Python 列表而已更适合用来做数学运算。下面是一个简单的小例子，向你展示标准列表对象和 NumPy 数组对象之间的差别：

In [13]:
>>> # Python list
>>> x = [1, 2, 3, 4]
>>> y = [5, 6, 7, 8]
>>> x * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [14]:
>>> x + 10

TypeError: can only concatenate list (not "int") to list

In [15]:
>>> x + y

[1, 2, 3, 4, 5, 6, 7, 8]

In [18]:
>>> # Numpy arrays
>>> import numpy as np
>>> ax = np.array([1, 2, 3, 4])
>>> ay = np.array([5, 6, 7, 8])
>>> ax * 2

array([2, 4, 6, 8])

In [20]:
>>> ax + 10

array([11, 12, 13, 14])

In [21]:
>>> ax + ay 

array([ 6,  8, 10, 12])

In [22]:
>>> ax * ay

array([ 5, 12, 21, 32])

    正如所见，两种方案中数组的基本数学运算结构并不相同。特别的，NumPy 中的标量运算 (比如 ax * 2 或 ax + 10 ) 会作用在每一个元素上。另外，当两个操作数都是数组的时候执行元素对等位置计算，并最终生成一个新的数组。
    
    对整个数组中所有元素同时执行数学运算可以使得作用在整个数组上的函数运算 简单而又快速。比如，如果你想计算多项式的值，可以这样做：

In [23]:
>>> def f(x):
        return 3*x**2 - 2*x + 7

>>> f(ax)

array([ 8, 15, 28, 47])

    NumPy 还为数组操作提供了大量的通用函数，这些函数可以作为 math 模块中类似函数的替代。比如：

In [24]:
>>> np.sqrt(ax)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [25]:
>>> np.cos(ax)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

    使用这些通用函数要比循环数组并使用 math 模块中的函数执行计算要快的多。因此，只要有可能的话尽量选择 NumPy 的数组方案。
    
    底层实现中，NumPy 数组使用了 C 或者 Fortran 语言的机制分配内存。也就是说，它们是一个非常大的连续的并由同类型数据组成的内存区域。所以，你可以构造一个比普通 Python 列表大的多的数组。比如，如果你想构造一个 10,000*10,000 的浮点数二 维网格，很轻松:

In [26]:
>>> grid = np.zeros(shape=(10000, 10000), dtype = float)
>>> grid

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

    关于 NumPy 有一点需要特别的主意，那就是它扩展 Python 列表的索引功能 - 特别是对于多维数组。为了说明清楚，先构造一个简单的二维数组并试着做些试验：

In [29]:
>>> a = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
>>> a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
>>> # Select row 1
>>> a[1]

array([5, 6, 7, 8])

In [31]:
>>> # Select column 1
>>> a[:,1]

array([ 2,  6, 10])

In [32]:
>>> # Select a subregion and change it
>>> a[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [34]:
>>> a[1:3, 1:3] += 10
>>> a

array([[ 1,  2,  3,  4],
       [ 5, 26, 27,  8],
       [ 9, 30, 31, 12]])

In [35]:
>>> # Broadcast a row vector across an operation on all rows
>>> a + [100, 101, 102, 103]

array([[101, 103, 105, 107],
       [105, 127, 129, 111],
       [109, 131, 133, 115]])

In [36]:
>>> a

array([[ 1,  2,  3,  4],
       [ 5, 26, 27,  8],
       [ 9, 30, 31, 12]])

In [37]:
>>> # Conditional assignment on an array
>>> np.where(a < 10, a, 10)

array([[ 1,  2,  3,  4],
       [ 5, 10, 10,  8],
       [ 9, 10, 10, 10]])

**讨论**

    NumPy 是 Python 领域中很多科学与工程库的基础，同时也是被广泛使用的最大最复杂的模块。即便如此，在刚开始的时候通过一些简单的例子和玩具程序也能帮我们完成一些有趣的事情。
    
    通常我们导入 NumPy 模块的时候会使用语句 import numpy as np 。这样的话你就不用再你的程序里面一遍遍的敲入 numpy ，只需要输入 np 就行了，节省了不少时间。
    
    如果想获取更多的信息，你当然得去 NumPy 官网逛逛了，网址是：http://www.numpy.org

## 10、矩阵与线性代数运算

**问题** 

    你需要执行矩阵和线性代数运算，比如矩阵乘法、寻找行列式、求解线性方程组等等。
    
**解决方案**

    NumPy 库有一个矩阵对象可以用来解决这个问题。

In [38]:
>>> import numpy as np
>>> m = np.matrix([[1, -2, 3],[0, 4, 5],[7,8,-9]])
>>> m

matrix([[ 1, -2,  3],
        [ 0,  4,  5],
        [ 7,  8, -9]])

In [39]:
>>> # Return transpose
>>> m.T

matrix([[ 1,  0,  7],
        [-2,  4,  8],
        [ 3,  5, -9]])

In [40]:
>>> # Return inverse
>>> m.I

matrix([[ 0.33043478, -0.02608696,  0.09565217],
        [-0.15217391,  0.13043478,  0.02173913],
        [ 0.12173913,  0.09565217, -0.0173913 ]])

In [42]:
>>> # Create a vector and multiply
>>> v = np.matrix([[2],[3],[4]])
>>> v

matrix([[2],
        [3],
        [4]])

In [43]:
>>> m * v

matrix([[ 8],
        [32],
        [ 2]])

    可以在 numpy.linalg 子包中找到更多的操作函数。
    
**讨论**

    很显然线性代数是个非常大的主题，已经超出了本书能讨论的范围。但是，如果你需要操作数组和向量的话，NumPy 是一个不错的入口点。可以访问 NumPy 官网 http://www.numpy.org 获取更多信息。

## 11、随机选择

**问题** 

    你想从一个序列中随机抽取若干元素，或者想生成几个随机数。
    
**解决方案**

    random模块有大量的函数用来产生随机数和随机选择元素。比如，要想从一个序列中随机的抽取一个元素，可以使用 random.choice() ：

In [44]:
>>> import random
>>> values = [1, 2, 3, 4, 5, 6]
>>> random.choice(values)

5

    为了提取出 N 个不同元素的样本，可以使用 random.sample()

In [45]:
>>> random.sample(values, 2)

[1, 2]

In [47]:
>>> random.sample(values, 4)

[1, 2, 5, 3]

    如果你只是想打乱序列中元素的顺序，可以使用 random.shuffle():

In [50]:
>>> random.shuffle(values)
>>> values

[5, 3, 1, 2, 6, 4]

    生产随机整数，请使用 random.randint():

In [51]:
>>> random.randint(0, 10)

1

    为了生成 0 到 1 范围内均匀分布的浮点数，使用 random.random():

In [53]:
>>> random.random()

0.25999967568623816

    如果要获取 N 位随机位 (二进制) 的整数，使用 random.getrandbits() ：

In [56]:
>>> random.getrandbits(16)

29774

**讨论**

    andom 模块使用 Mersenne Twister 算法来计算生成随机数。这是一个确定性算法，但是你可以通过 random.seed() 函数修改初始化种子

In [57]:
random.seed() # Seed based on system time or os.urandom() 
random.seed(12345) # Seed based on integer given 
random.seed(b'bytedata') # Seed based on byte data

    除了上述介绍的功能，random 模块还包含基于均匀分布、高斯分布和其他分布的随机数生成函数。比如，random.uniform() 计算均匀分布随机数，random.gauss() 计算正态分布随机数。对于其他的分布情况请参考在线文档。
    
    在 random 模块中的函数不应该用在和密码学相关的程序中。如果你确实需要类似的功能，可以使用 ssl 模块中相应的函数。比如，ssl.RAND_bytes() 可以用来生成一个安全的随机字节序列。

## 12、基本的日期与实践转换

**问题** 

    你需要执行简单的时间转换，比如天到秒，小时到分钟等的转换。
    
**解决方案**

    为了执行不同时间单位的转换和计算，请使用 datetime 模块。比如，为了表示一个时间段，可以创建一个 timedelta 实例，就像下面这样：

In [60]:
>>> from datetime import timedelta
>>> a = timedelta(days=2, hours=6)
>>> b = timedelta(hours=4.5)
>>> c = a + b
>>> c.days

2

In [61]:
>>> c.seconds

37800

In [63]:
>>> c.seconds / 3600

10.5

In [64]:
>>> c.total_seconds() / 3600

58.5

    如果你想表示指定的日期和事件，先创建一个 datetime 实例然后使用标准的教学运算来操作它们。比如：

In [65]:
>>> from datetime import datetime
>>> a = datetime(2012, 9, 23)
>>> print(a + timedelta(days=10))

2012-10-03 00:00:00


In [68]:
>>> b = datetime(2012, 12, 21)
>>> d = b - a
>>> d.days

89

In [70]:
>>> nows = datetime.today()
>>> print(nows)

2020-11-18 15:28:31.969873


    在计算的时候，需要注意的是 datetime 会自动处理闰年。比如：

In [72]:
>>> a = datetime(2012, 3, 1)
>>> b = datetime(2012, 2, 28)
>>> a - b

datetime.timedelta(days=2)

In [73]:
>>> (a-b).days

2

    对大多数基本的日期和时间处理问题，datetime 模块已经足够了。如果你需要执行更加复杂的日期操作，比如处理时区，模糊时间范围，节假日计算等等，可以考虑使 用 dateutil 模块
    
    许多类似的时间计算可以使用 dateutil.relativedelta() 函数代替。但是，有一点需要注意的就是，它会在处理月份 (还有它们的天数差距) 的时候填充间隙。看例子最清楚：
    

In [74]:
>>> a = datetime(2012, 9, 23)
>>> a + timedelta(months=1)

TypeError: 'months' is an invalid keyword argument for __new__()

In [78]:
>>> from dateutil.relativedelta import relativedelta
>>> a + relativedelta(months=+1)

datetime.datetime(2012, 10, 23, 0, 0)

In [79]:
>>> a + relativedelta(months=+4)

datetime.datetime(2013, 1, 23, 0, 0)

In [81]:
>>> # Time between two dates 
>>> b = datetime(2012, 12, 21)
>>> d = b - a
>>> d

datetime.timedelta(days=89)

In [82]:
>>> d = relativedelta(b, a) 
>>> d

relativedelta(months=+2, days=+28)

In [83]:
>>> d.months 

2

## 13、计算最后一个周五的日期

**问题** 

    你需要查找星期中某一天最后出现的日期，比如星期五。
    
**解决方案**

    Python 的 datetime 模块中有工具函数和类可以帮助你执行这样的计算。下面是对类似这样的问题的一个通用解决方案：

In [1]:
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
"""
Topic: 最后的周五
Desc :
"""
from datetime import datetime, timedelta

weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday',
            'Friday', 'Saturday', 'Sunday']


def get_previous_byday(dayname, start_date=None):
    if start_date is None:
        start_date = datetime.today()
    day_num = start_date.weekday()
    day_num_target = weekdays.index(dayname)
    days_ago = (7 + day_num - day_num_target) % 7
    if days_ago == 0:
        days_ago = 7
    target_date = start_date - timedelta(days=days_ago)
    return target_date

In [2]:
>>> datetime.today()

datetime.datetime(2020, 11, 18, 18, 45, 33, 112549)

In [3]:
>>> get_previous_byday('Monday')

datetime.datetime(2020, 11, 16, 18, 46, 27, 870526)

In [5]:
>>> get_previous_byday('Friday') # Previous week, not today

datetime.datetime(2020, 11, 13, 18, 46, 49, 927781)

    可选的 start_date 参数可以由另外一个 datetime 实例来提供。比如：

In [7]:
>>> get_previous_byday('Sunday', datetime(2020, 11, 18))

datetime.datetime(2020, 11, 15, 0, 0)

**讨论**

    上面的算法原理是这样的：先将开始日期和目标日期映射到星期数组的位置上 (星期一索引为 0)，然后通过模运算计算出目标日期要经过多少天才能到达开始日期。然后用开始日期减去那个时间差即得到结果日期。
    
    如果你要像这样执行大量的日期计算的话，你最好安装第三方包 python-dateutil来代替。比如，下面是是使用 dateutil 模块中的 relativedelta() 函数执行同样的计算：

In [8]:
>>> from datetime import datetime
>>> from dateutil.relativedelta import relativedelta
>>> from dateutil.rrule import *
>>> d = datetime.now()
>>> print(d)

2020-11-18 18:54:05.486058


In [9]:
>>> # Next Friday
>>> print(d + relativedelta(weekday=FR))

2020-11-20 18:54:05.486058


In [10]:
>>> # Last Friday
>>> print(d + relativedelta(weekday=FR(-1)))

2020-11-13 18:54:05.486058
